/* Everything that leaves the app: image, vector, instructions, template. */

import { nailTable, saveBlob, FILE_TYPES, fmtLength } from './util.js';
import { renderResult, threadWidth } from './render.js';

const stamp = () => new Date().toISOString().slice(0, 16).replace(/[:T]/g, '-');

/* ── raster ─────────────────────────────────────────────────── */
export async function exportPNG(result, size = 2000) {
  const c = document.createElement('canvas');
  renderResult(c, result.layers, { ...result.opts, size });
  const blob = await new Promise((res) => c.toBlob(res, 'image/png'));
  return saveBlob(blob, `string-art-${stamp()}.png`, { id: 'sa-png', types: FILE_TYPES.png });
}

/* ── vector ─────────────────────────────────────────────────── */
export function buildSVG(result, size = 1000) {
  const { nails, offsetRad, bg, workRes } = result.opts;
  const P = nailTable(nails, offsetRad).map((p) => ({
    x: +(p.x * size).toFixed(2), y: +(p.y * size).toFixed(2),
  }));
  const w = +threadWidth(size, workRes).toFixed(3);

  // One <line> per chord, not one long polyline: a single path would be
  // composited once, so crossings would not accumulate darkness.
  const paths = result.layers.map((L) => {
    if (L.path.length < 2) return '';
    const segs = [];
    for (let i = 1; i < L.path.length; i++) {
      const a = P[L.path[i - 1]], b = P[L.path[i]];
      segs.push(`<line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}"/>`);
    }
    return `<g stroke="${L.color}" stroke-opacity="${L.alpha}" stroke-width="${w}"` +
           ` stroke-linecap="round">\n${segs.join('\n')}\n</g>`;
  }).join('\n');

  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${size} ${size}" width="${size}" height="${size}">
<title>String art — ${result.stats.lines} lines, ${nails} nails</title>
<circle cx="${size / 2}" cy="${size / 2}" r="${size / 2}" fill="${bg}"/>
<g>
${paths}
</g>
</svg>`;
}

export function exportSVG(result) {
  return saveBlob(new Blob([buildSVG(result)], { type: 'image/svg+xml' }),
    `string-art-${stamp()}.svg`, { id: 'sa-svg', types: FILE_TYPES.svg });
}

/* ── instructions ───────────────────────────────────────────── */
export function buildSequenceText(result) {
  const { nails, boardMM } = result.opts;
  const L = [];
  L.push('STRING ART — THREADING SEQUENCE');
  L.push('='.repeat(46));
  L.push(`Nails            ${nails}, evenly spaced`);
  L.push(`Board diameter   ${fmtLength(boardMM)}`);
  L.push(`Nail spacing     ${fmtLength((Math.PI * boardMM) / nails)} along the rim`);
  L.push(`Total lines      ${result.stats.lines}`);
  L.push(`Thread needed    ${fmtLength(result.stats.threadMM)}  (add ~10% slack)`);
  L.push(`Image match      ${(result.stats.match * 100).toFixed(1)}%`);
  L.push('');
  L.push('Nails are numbered 0 to ' + (nails - 1) + ', counting clockwise on screen');
  L.push('from the first-nail mark on the template.');
  L.push('');

  result.layers.forEach((layer, li) => {
    L.push('-'.repeat(46));
    L.push(`THREAD ${li + 1} of ${result.layers.length}   colour ${layer.color}   ` +
           `${layer.path.length - 1} lines`);
    L.push('-'.repeat(46));
    L.push(`Tie on at nail ${layer.path[0]}, then go around:`);
    L.push('');
    for (let i = 1; i < layer.path.length; i += 10) {
      const row = layer.path.slice(i, i + 10);
      L.push(String(i).padStart(6) + '  ' + row.map((n) => String(n).padStart(4)).join(''));
    }
    L.push('');
  });
  L.push('Generated by String Art Studio — ' + new Date().toLocaleString());
  return L.join('\n');
}

export function exportTXT(result) {
  return saveBlob(new Blob([buildSequenceText(result)], { type: 'text/plain' }),
    `string-art-sequence-${stamp()}.txt`, { id: 'sa-txt', types: FILE_TYPES.txt });
}

export function buildCSV(result) {
  const rows = ['step,thread,colour,from_nail,to_nail'];
  let step = 0;
  result.layers.forEach((layer, li) => {
    for (let i = 1; i < layer.path.length; i++) {
      rows.push(`${++step},${li + 1},${layer.color},${layer.path[i - 1]},${layer.path[i]}`);
    }
  });
  return rows.join('\n');
}

export function exportCSV(result) {
  return saveBlob(new Blob([buildCSV(result)], { type: 'text/csv' }),
    `string-art-sequence-${stamp()}.csv`, { id: 'sa-csv', types: FILE_TYPES.csv });
}

export function exportJSON(result) {
  const doc = {
    generator: 'String Art Studio',
    created: new Date().toISOString(),
    board: {
      nails: result.opts.nails,
      diameterMM: result.opts.boardMM,
      firstNailAngleDeg: (result.opts.offsetRad * 180) / Math.PI,
      colour: result.opts.bg,
    },
    stats: result.stats,
    settings: result.settings,
    threads: result.layers.map((L) => ({ colour: L.color, opacity: L.alpha, path: L.path })),
  };
  return saveBlob(new Blob([JSON.stringify(doc, null, 2)], { type: 'application/json' }),
    `string-art-${stamp()}.json`, { id: 'sa-json', types: FILE_TYPES.json });
}

export async function copySequence(result) {
  const txt = result.layers
    .map((L, i) => `# thread ${i + 1} (${L.color})\n${L.path.join(', ')}`)
    .join('\n\n');
  await navigator.clipboard.writeText(txt);
}

/* ── printable nail template ────────────────────────────────── */
/** True-scale SVG in millimetres — print at 100% and use it as a drilling guide. */
export function buildTemplateSVG(nails, boardMM, offsetRad) {
  const pad = 14;
  const total = boardMM + pad * 2;
  const R = boardMM / 2, cx = total / 2, cy = total / 2;
  const P = nailTable(nails, offsetRad);
  const every = nails > 300 ? 20 : nails > 140 ? 10 : 5;
  const fs = Math.max(2, Math.min(4.5, (Math.PI * boardMM) / nails * 1.5));

  const marks = [];
  for (let i = 0; i < nails; i++) {
    const x = pad + P[i].x * boardMM, y = pad + P[i].y * boardMM;
    const a = Math.atan2(y - cy, x - cx);
    const major = i % every === 0;
    marks.push(`<circle cx="${x.toFixed(3)}" cy="${y.toFixed(3)}" r="${major ? 0.7 : 0.45}" fill="#000"/>`);
    marks.push(`<line x1="${(cx + Math.cos(a) * (R - 2.6)).toFixed(3)}" y1="${(cy + Math.sin(a) * (R - 2.6)).toFixed(3)}" x2="${(cx + Math.cos(a) * (R - 0.9)).toFixed(3)}" y2="${(cy + Math.sin(a) * (R - 0.9)).toFixed(3)}" stroke="#000" stroke-width="${major ? 0.35 : 0.16}"/>`);
    if (major) {
      const tx = cx + Math.cos(a) * (R + 3.4), ty = cy + Math.sin(a) * (R + 3.4);
      marks.push(`<text x="${tx.toFixed(2)}" y="${ty.toFixed(2)}" font-size="${fs.toFixed(2)}" font-family="monospace" text-anchor="middle" dominant-baseline="middle" fill="#000">${i}</text>`);
    }
  }

  const first = P[0];
  const fx = pad + first.x * boardMM, fy = pad + first.y * boardMM;

  // A4 is 210 mm wide; anything past that needs poster/tiled printing.
  const oversize = total > 200
    ? `<text x="${cx}" y="${(total - 9).toFixed(1)}" font-size="3" font-family="monospace" text-anchor="middle" fill="#000">Larger than A4 — print as a poster tiled across pages, or use the rim spacing below</text>
<text x="${cx}" y="${(pad - 9).toFixed(1)}" font-size="3" font-family="monospace" text-anchor="middle" fill="#000">Rim spacing between neighbouring nails: ${((Math.PI * boardMM) / nails).toFixed(2)} mm  ·  rim length ${(Math.PI * boardMM).toFixed(0)} mm</text>`
    : '';

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${total}mm" height="${total}mm" viewBox="0 0 ${total} ${total}">
<title>Nail template — ${nails} nails, ${boardMM.toFixed(1)} mm diameter</title>
<rect width="${total}" height="${total}" fill="#fff"/>
<circle cx="${cx}" cy="${cy}" r="${R}" fill="none" stroke="#000" stroke-width="0.3"/>
<circle cx="${cx}" cy="${cy}" r="${R - 2.6}" fill="none" stroke="#999" stroke-width="0.12"/>
<line x1="${cx - 5}" y1="${cy}" x2="${cx + 5}" y2="${cy}" stroke="#000" stroke-width="0.3"/>
<line x1="${cx}" y1="${cy - 5}" x2="${cx}" y2="${cy + 5}" stroke="#000" stroke-width="0.3"/>
<circle cx="${fx.toFixed(3)}" cy="${fy.toFixed(3)}" r="1.7" fill="none" stroke="#000" stroke-width="0.4"/>
<line x1="${pad}" y1="${(total - 4).toFixed(1)}" x2="${(pad + 100).toFixed(1)}" y2="${(total - 4).toFixed(1)}" stroke="#000" stroke-width="0.3"/>
<line x1="${pad}" y1="${(total - 6).toFixed(1)}" x2="${pad}" y2="${(total - 2).toFixed(1)}" stroke="#000" stroke-width="0.3"/>
<line x1="${(pad + 100).toFixed(1)}" y1="${(total - 6).toFixed(1)}" x2="${(pad + 100).toFixed(1)}" y2="${(total - 2).toFixed(1)}" stroke="#000" stroke-width="0.3"/>
<text x="${(pad + 50).toFixed(1)}" y="${(total - 5.5).toFixed(1)}" font-size="3" font-family="monospace" text-anchor="middle" fill="#000">100 mm check bar — print at 100% scale</text>
<text x="${cx}" y="${(pad - 5).toFixed(1)}" font-size="3.6" font-family="monospace" text-anchor="middle" fill="#000">${nails} nails · ${boardMM.toFixed(0)} mm diameter · nail 0 is circled</text>
${oversize}
${marks.join('\n')}
</svg>`;
}

export function exportTemplate(result) {
  const { nails, boardMM, offsetRad } = result.opts;
  const svg = buildTemplateSVG(nails, boardMM, offsetRad);
  return saveBlob(new Blob([svg], { type: 'image/svg+xml' }),
    `nail-template-${nails}-${Math.round(boardMM)}mm.svg`,
    { id: 'sa-template', types: FILE_TYPES.svg });
}
